---
- name: Process GitLab push event
  hosts: localhost

  tasks:
    - name: Print ansible_eda
      ansible.builtin.debug:
        var: ansible_eda
      when: ansible_eda is defined

    - name: Print repo and time stamp information
      ansible.builtin.debug:
        msg: "Responding to push event on GitLab repository {{ ansible_eda.event.payload.repository.git_http_url }} at {{ ansible_eda.event.payload.commits[0].timestamp }}"
      when: ansible_eda is defined
