---
- name: Act on GitLab webhook push event
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Execute gitlab-push-event.yml playbook
      condition: event.payload.object_kind == "push"
      action:
        run_job_template:
          name: AAP - Update Templates
          organization: Default
