---
- name: Act on webhook events
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Execute say-hello.yml playbook
      condition: event.meta is defined
      action:
        run_job_template:
          name: EDA - Hello
          organization: Default

#      condition: event.payload.message == "Ansible is super cool"
